### ISSUE TITLE
Подпись запроса "ik_sign" не верна

### ISSUE THREAD

**Issue by nareshalka** [interkassa/php-sdk#1]
Добрый день. При переходе по сформированной ссылке выдается ошибка "Подпись запроса "ik_sign" не верна".
Алгоритм подписи в личном кабинете Интеркассы: sha256
![image](https://user-images.githubusercontent.com/89643425/159157178-37c9b3d0-0ba7-4502-9af7-5f46a6a8b8b9.png)

**Comment by nareshalka** [comment]
Изменил функцию makeSignature, помогло, страница с оплатой открывается, но прошу в любом случае помочь мне.
```
public static function makeSignature(array $data, string $key, $algorithm = 'md5'): string
    {
        $data = self::sortByKeyRecursive($data);
        $data[] = $key;
        $signString = self::implodeRecursive(':', $data);

        return $algorithm === 'sha256'
            ? base64_encode(md5($signString, true))
            : base64_encode(hash('sha256', $signString, true));

//        return $algorithm === 'md5'
//            ? base64_encode(md5($signString, true))
//            : base64_encode(hash('sha256', $signString, true));
    }
```
UPD: с тестовым ключом даже такой вариант не работает, с реальным вроде нормально

**Comment by PechenkaPM** [comment]
Верните функцию в первоначальный вид, вам нужно сделать вот так:
`$configuration->setAlgorithm("sha256");`

**Comment by georgiy0804** [comment]
Благодарю за помощь!
